# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: destroyed-symlinks
      - id: detect-private-key

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.3.7
    hooks:
      - id: ansible-lint
        always_run: false
        pass_filenames: true
        files: \.(yaml|yml)$
        # yamllint disable-line rule:line-length
        entry: env ANSIBLE_LIBRARY=./plugins/modules ANSIBLE_MODULE_UTILS=./plugins/module_utils ansible-lint --force-color

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.25.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.0.0
    hooks:
      - id: doctoc
        args: ['--github']

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.10
    hooks:
      - id: cmake-format
      - id: cmake-lint

  - repo: https://git.shore.co.il/nimrod/docker-pre-commit.git
    rev: v0.3.0
    hooks:
      - id: hadolint
      - id: docker-compose
      - id: dockerfile-lint
